grep -C 0 "MySQLTransactionRollbackException" rebate_calculate_error.log

[root@cluster-platform-docker-58 logs]# grep -C 50 "MySQLTransactionRollbackException" rebate_calculate_error.log
        at net.jplugin.core.ctx.impl.RuleInterceptor.invoke(RuleInterceptor.java:134)
        at com.sun.proxy.$Proxy45.success(Unknown Source)
        at com.haiziwang.rebate.calculate.yearreturn.task.YearReturnTaskServlet.lambda$null$11(YearReturnTaskServlet.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor2744.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.jplugin.core.das.mybatis.impl.MapperProxyFactory$InvocationHandler4Mapper.invoke(MapperProxyFactory.java:49)
        ... 26 more
Caused by: org.apache.ibatis.exceptions.PersistenceException:
### Error updating database.  Cause: java.lang.RuntimeException: Deadlock found when trying to get lock; try restarting transaction
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: update yearreturn_fee_head_2020 set del_flag=? where batch_no = ? and contract_no in          (               ?          ,              ?          )
### Cause: java.lang.RuntimeException: Deadlock found when trying to get lock; try restarting transaction
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:154)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:54)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
        at com.sun.proxy.$Proxy89.updateDelFlagByBatchNoAndcontractNo(Unknown Source)
        ... 30 more
Caused by: java.lang.RuntimeException: Deadlock found when trying to get lock; try restarting transaction
        at net.jplugin.common.kits.filter.FilterManager.filter(FilterManager.java:47)
        at net.jplugin.core.das.monitor.SqlMonitor.execute(SqlMonitor.java:38)
        at net.jplugin.core.das.monitor.StatemenWrapper.execute(StatemenWrapper.java:153)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:44)
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:69)
        at sun.reflect.GeneratedMethodAccessor354.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
        at com.sun.proxy.$Proxy129.update(Unknown Source)
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:48)
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:105)
        at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:71)
        at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
        at com.sun.proxy.$Proxy127.update(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:62)
        at com.sun.proxy.$Proxy127.update(Unknown Source)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:152)
        ... 33 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:950)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:198)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:198)
        at net.jplugin.core.das.monitor.StatemenWrapper.lambda$2(StatemenWrapper.java:153)
        at net.jplugin.core.das.monitor.SqlMonitor.lambda$0(SqlMonitor.java:18)
        at net.jplugin.common.kits.filter.FilterChain.next(FilterChain.java:32)
        at com.hzw.monitor.report.chain.SQLExeFilter4TraceReport.filter(SQLExeFilter4TraceReport.java:38)
        at com.hzw.monitor.report.chain.SQLExeFilter4TraceReport.filter(SQLExeFilter4TraceReport.java:25)
        at net.jplugin.common.kits.filter.FilterChain.next(FilterChain.java:32)
        at net.jplugin.common.kits.filter.FilterManager.filter(FilterManager.java:42)
        ... 56 more
2020-10-22 11:45:25,451 149970748 ERROR [pool-87-thread-1] com.haiziwang.rebate.api.util.MailUtil     - The contents of email: task id=36867,batchNo=20201022001,contractNo=201707070001,cause=MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
